### ISSUE TITLE
Error when I try to convert

### ISSUE THREAD

**Issue by kpbird** [coolaj86/blogger2jekyll#12]
/usr/local/lib/node_modules/blogger2jekyll/lib/index.js:245
          post.comments.push(comment);
              ^
TypeError: Cannot read property 'comments' of undefined
    at /usr/local/lib/node_modules/blogger2jekyll/lib/index.js:245:15
    at Array.forEach (native)
    at translateFile (/usr/local/lib/node_modules/blogger2jekyll/lib/index.js:145:22)
    at Parser.<anonymous> (/usr/local/lib/node_modules/blogger2jekyll/node_modules/xml2js/lib/xml2js.js:255:20)
    at Parser.emit (events.js:95:17)
    at Object.saxParser.onclosetag (/usr/local/lib/node_modules/blogger2jekyll/node_modules/xml2js/lib/xml2js.js:225:24)
    at emit (/usr/local/lib/node_modules/blogger2jekyll/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/lib/node_modules/blogger2jekyll/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/local/lib/node_modules/blogger2jekyll/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/usr/local/lib/node_modules/blogger2jekyll/node_modules/xml2js/node_modules/sax/lib/sax.js:1293:29)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/blogger2jekyll/node_modules/xml2js/lib/xml2js.js:273:29)

**Comment by lolobosse** [comment]
+1, same here

**Comment by rebolyte** [comment]
:+1:

**Comment by Aziraphale81** [comment]
I'm getting the same error.

**Comment by rmsaitam** [comment]
same error. Somebody managed to solve?
